// 基础项目：工程模板与基础设施
export const BaseProject = [
  {
    text: "基础项目",
    link: "/project/Base/index.md",
    items: [
      {
        text: "Vue3 模板",
        link: "/project/Base/Vue3Template/index.md",
        collapsed: true,
        items: [
          { text: "初始化项目", link: "/project/Base/Vue3Template/InitProject/index.md" },
          { text: "配置环境变量", link: "/project/Base/Vue3Template/Env/index.md" },
          { text: "拆分配置", link: "/project/Base/Vue3Template/SplitConfig/index.md" },
          { text: "配置打包构建优化", link: "/project/Base/Vue3Template/Build/index.md" },
          { text: "封装 Pinia", link: "/project/Base/Vue3Template/Pinia/index.md" },
          { text: "配置自动路由", link: "/project/Base/Vue3Template/Router/index.md" },
          { text: "配置自动导入", link: "/project/Base/Vue3Template/AutoImport/index.md" },
          { text: "配置组件自动注册", link: "/project/Base/Vue3Template/AutoComponent/index.md" },
          { text: "配置 VueUse 工具集", link: "/project/Base/Vue3Template/VueUse/index.md" },
          { text: "配置 VueRequest", link: "/project/Base/Vue3Template/VueRequest/index.md" },
          { text: "配置国际化", link: "/project/Base/Vue3Template/i18n/index.md" },
          { text: "自定义配置网络请求", link: "/project/Base/Vue3Template/Http/index.md" },
          { text: "权限模块", link: "/project/Base/Vue3Template/Permission/index.md" },
          { text: "主题模块", link: "/project/Base/Vue3Template/Theme/index.md" },
          { text: "组件库集成", link: "/project/Base/Vue3Template/ComponentLibrary/index.md" },
          { text: "配置 CSS 代码检查工具", link: "/project/Base/Vue3Template/Stylelint/index.md" },
          { text: "配置 SCSS", link: "/project/Base/Vue3Template/SCSS/index.md" },
          { text: "配置 UnoCSS", link: "/project/Base/Vue3Template/UnoCSS/index.md" },
          { text: "发布模块", link: "/project/Base/Vue3Template/Release/index.md" },
          { text: "常见问题与最佳实践", link: "/project/Base/Vue3Template/FAQ/index.md" },
        ],
      },
      {
        text: "后端通用模板",
        link: "/project/Base/BackendTemplate/index.md",
        collapsed: true,
        items: [
          { text: "需求与架构设计", link: "/project/Base/BackendTemplate/Architecture/index.md" },
          { text: "骨架与目录结构", link: "/project/Base/BackendTemplate/Skeleton/index.md" },
          { text: "统一响应与全局异常", link: "/project/Base/BackendTemplate/CommonResponse/index.md" },
          { text: "健康检查与配置", link: "/project/Base/BackendTemplate/HealthCheck/index.md" },
          { text: "请求追踪 ID 与日志切面", link: "/project/Base/BackendTemplate/TraceId/index.md" },
          { text: "参数校验增强", link: "/project/Base/BackendTemplate/Validation/index.md" },
          { text: "MockMvc 集成测试", link: "/project/Base/BackendTemplate/IntegrationTest/index.md" },
          { text: "数据访问：MyBatis-Plus 接入", link: "/project/Base/BackendTemplate/DataAccess/index.md" },
          { text: "认证授权：Spring Security 7 + JWT", link: "/project/Base/BackendTemplate/Security/index.md" },
          { text: "登录业务闭环与令牌生命周期", link: "/project/Base/BackendTemplate/AuthLifecycle/index.md" },
          { text: "压测与性能基线", link: "/project/Base/BackendTemplate/PerformanceTest/index.md" },
          { text: "测试数据隔离与边界用例", link: "/project/Base/BackendTemplate/TestIsolation/index.md" },
          { text: "技术栈可插拔：模块边界与选择器脚本", link: "/project/Base/BackendTemplate/StackSelect/index.md" },
          { text: "模板 CLI：设计与路线图", link: "/project/Base/BackendTemplate/TemplateCli/index.md" },
          { text: "异常路径联调收口与用例清单", link: "/project/Base/BackendTemplate/ErrorPath/index.md" },
          { text: "容器化：多阶段镜像与 Compose 编排", link: "/project/Base/BackendTemplate/Deployment/index.md" },
          { text: "CI 流水线：把门禁串成一条链", link: "/project/Base/BackendTemplate/CI/index.md" },
          { text: "镜像推送与发布策略", link: "/project/Base/BackendTemplate/Release/index.md" },
          { text: "主库可插拔：MySQL / PostgreSQL 双方言", link: "/project/Base/BackendTemplate/Database/index.md" },
          { text: "上线验收与监控接入", link: "/project/Base/BackendTemplate/Acceptance/index.md" },
          { text: "统一门禁：清单收敛为单一来源", link: "/project/Base/BackendTemplate/Gates/index.md" },
          { text: "进展记录", link: "/project/Base/BackendTemplate/Progress/index.md" },
        ],
      },
      {
        text: "Nuxt 通用模板",
        link: "/project/Base/NuxtTemplate/index.md",
        collapsed: true,
        items: [
          { text: "需求与方案定位", link: "/project/Base/NuxtTemplate/Requirement/index.md" },
          { text: "零依赖引导期骨架", link: "/project/Base/NuxtTemplate/Bootstrap/index.md" },
          { text: "引导页：信息架构与选择模型", link: "/project/Base/NuxtTemplate/WizardFrontend/index.md" },
          { text: "引导器服务端与安全边界", link: "/project/Base/NuxtTemplate/WizardBackend/index.md" },
          { text: "初始化引擎：自删除与依赖安装", link: "/project/Base/NuxtTemplate/InitEngine/index.md" },
          { text: "技术栈矩阵与组合兼容", link: "/project/Base/NuxtTemplate/StackMatrix/index.md" },
          { text: "初始化后的应用基线", link: "/project/Base/NuxtTemplate/AppBaseline/index.md" },
          { text: "质量门禁与自测", link: "/project/Base/NuxtTemplate/Quality/index.md" },
          { text: "构建与产物形态", link: "/project/Base/NuxtTemplate/Build/index.md" },
          { text: "部署与上线", link: "/project/Base/NuxtTemplate/Deployment/index.md" },
          { text: "验收与上线检查", link: "/project/Base/NuxtTemplate/Acceptance/index.md" },
          { text: "进展记录", link: "/project/Base/NuxtTemplate/Progress/index.md" },
        ],
      },
      {
        text: "后台管理系统通用模板",
        link: "/project/Base/AdminTemplate/index.md",
        collapsed: true,
        items: [
          { text: "需求与方案定位", link: "/project/Base/AdminTemplate/Requirement/index.md" },
          { text: "初始化：从 NuxtTemplate 拿到基线", link: "/project/Base/AdminTemplate/Bootstrap/index.md" },
          { text: "技术栈适配层", link: "/project/Base/AdminTemplate/StackAdapter/index.md" },
          { text: "后台骨架：双布局与菜单", link: "/project/Base/AdminTemplate/Skeleton/index.md" },
          { text: "登录与路由守卫", link: "/project/Base/AdminTemplate/Login/index.md" },
          { text: "进展记录", link: "/project/Base/AdminTemplate/Progress/index.md" },
        ],
      },
    ],
  },
];

// 完整项目：端到端交付实战
export const CompleteProject = [
  {
    text: "完整项目",
    link: "/project/Complete/index.md",
    items: [
      { text: "完整项目总览", link: "/project/Complete/index.md" },
      {
        text: "全栈博客平台",
        link: "/project/Complete/BlogPlatform/index.md",
        collapsed: true,
        items: [
          { text: "项目总览", link: "/project/Complete/BlogPlatform/index.md" },
          { text: "需求拆分与验收条件", link: "/project/Complete/BlogPlatform/Requirements/index.md" },
          { text: "架构设计与技术选型", link: "/project/Complete/BlogPlatform/Architecture/index.md" },
          { text: "数据库设计", link: "/project/Complete/BlogPlatform/DatabaseDesign/index.md" },
          { text: "接口契约", link: "/project/Complete/BlogPlatform/Contract/index.md" },
          { text: "工程骨架与验收门禁", link: "/project/Complete/BlogPlatform/Skeleton/index.md" },
          { text: "文章写入链路", link: "/project/Complete/BlogPlatform/WritePath/index.md" },
          { text: "管理端认证与角色", link: "/project/Complete/BlogPlatform/AuthRoles/index.md" },
          { text: "文章下线动作", link: "/project/Complete/BlogPlatform/Lifecycle/index.md" },
          { text: "Markdown 渲染能力补齐", link: "/project/Complete/BlogPlatform/Rendering/index.md" },
          { text: "可见性收敛", link: "/project/Complete/BlogPlatform/Visibility/index.md" },
          { text: "测试分层收口", link: "/project/Complete/BlogPlatform/TestLayers/index.md" },
          { text: "判据收口与分类标签联调", link: "/project/Complete/BlogPlatform/Consolidation/index.md" },
          { text: "评论链路：两级楼层的建模与写入", link: "/project/Complete/BlogPlatform/Comments/index.md" },
          { text: "评论读侧：楼层分页、占位渲染与契约穷举", link: "/project/Complete/BlogPlatform/CommentRead/index.md" },
          { text: "全文搜索：MySQL ngram 先行", link: "/project/Complete/BlogPlatform/Search/index.md" },
          { text: "前台 SSR：服务端取数、hydration 一致与 SEO 元信息", link: "/project/Complete/BlogPlatform/FrontendSSR/index.md" },
          {
            text: "读者账号与权限",
            link: "/project/Complete/BlogPlatform/ReaderAccount/index.md",
            collapsed: true,
            items: [
              { text: "章节入口：一张表、两套身份、一条硬边界", link: "/project/Complete/BlogPlatform/ReaderAccount/index.md" },
              { text: "需求与验收条件（US-07 ~ US-11）", link: "/project/Complete/BlogPlatform/ReaderAccount/Requirements/index.md" },
              { text: "表设计：users 扩列与 user_tokens", link: "/project/Complete/BlogPlatform/ReaderAccount/DataModel/index.md" },
              { text: "接口设计：11 条路径与令牌轮换", link: "/project/Complete/BlogPlatform/ReaderAccount/API/index.md" },
              { text: "页面与登录态：Cookie、CSRF 与 SSR 缓存切分", link: "/project/Complete/BlogPlatform/ReaderAccount/Pages/index.md" },
              { text: "测试：A1~A10 与 account_smoke", link: "/project/Complete/BlogPlatform/ReaderAccount/Tests/index.md" },
              { text: "验收与第 3 周收尾", link: "/project/Complete/BlogPlatform/ReaderAccount/Acceptance/index.md" },
            ],
          },
          {
            text: "核心业务流收口",
            link: "/project/Complete/BlogPlatform/CoreFlow/index.md",
            collapsed: true,
            items: [
              { text: "章节入口：五个环节、一条身份主语", link: "/project/Complete/BlogPlatform/CoreFlow/index.md" },
              { text: "领域建模：三个聚合与事务边界", link: "/project/Complete/BlogPlatform/CoreFlow/DomainModel/index.md" },
              { text: "状态机驱动的业务流：转移 × 副作用矩阵", link: "/project/Complete/BlogPlatform/CoreFlow/StateMachine/index.md" },
              { text: "接口联调：跨模块字段依赖清单", link: "/project/Complete/BlogPlatform/CoreFlow/Integration/index.md" },
              { text: "端到端走查：五段时序与三个接缝", link: "/project/Complete/BlogPlatform/CoreFlow/EndToEnd/index.md" },
              { text: "一条龙回归：报告结构与 CF1~CF14", link: "/project/Complete/BlogPlatform/CoreFlow/Regression/index.md" },
              { text: "第 3 周验收结论与顺延项登记", link: "/project/Complete/BlogPlatform/CoreFlow/Acceptance/index.md" },
            ],
          },
          {
            text: "第 3 周收口",
            link: "/project/Complete/BlogPlatform/Week3Close/index.md",
            collapsed: true,
            items: [
              { text: "第 3 周收口：回归报告回填与第 4 周启动", link: "/project/Complete/BlogPlatform/Week3Close/index.md" },
            ],
          },
          {
            text: "一键部署",
            link: "/project/Complete/BlogPlatform/Deployment/index.md",
            collapsed: true,
            items: [
              { text: "一键部署：Compose 五服务与首次 DDL 实测", link: "/project/Complete/BlogPlatform/Deployment/index.md" },
            ],
          },
          {
            text: "监控接入",
            link: "/project/Complete/BlogPlatform/Monitoring/index.md",
            collapsed: true,
            items: [
              { text: "监控接入：指标口径、告警阈值与 traceId 串链", link: "/project/Complete/BlogPlatform/Monitoring/index.md" },
            ],
          },
          { text: "进展记录", link: "/project/Complete/BlogPlatform/Progress/index.md" },
        ],
      },
      {
        text: "全栈项目实战",
        link: "/project/Complete/FullStackProject/index.md",
        collapsed: true,
        items: [
          { text: "需求拆分", link: "/project/Complete/FullStackProject/Requirements/index.md" },
          { text: "数据库设计", link: "/project/Complete/FullStackProject/Database/index.md" },
          { text: "接口联调", link: "/project/Complete/FullStackProject/Api/index.md" },
          { text: "编码实现", link: "/project/Complete/FullStackProject/Development/index.md" },
          { text: "测试", link: "/project/Complete/FullStackProject/Testing/index.md" },
          { text: "部署", link: "/project/Complete/FullStackProject/Deployment/index.md" },
          { text: "复盘", link: "/project/Complete/FullStackProject/Retrospective/index.md" },
        ],
      },
    ],
  },
];
